mutation AddShoppingList($done: Boolean = false, $product: String!, $addedBy: String!) {
  insertOneShoppingList(data: { done: $done, product: $product, addedBy: $addedBy }) {
    _id
    addedBy
    done
    product
  }
}
